#!/usr/bin/with-contenv bash

umask 022

# Copy the autoProcess.ini script from mp4_automator if not available
[[ ! -f /mp4automator/autoProcess.ini ]] && (cp /mp4automator/autoProcess.ini.sample /mp4automator/autoProcess.ini)

# Copy the NZBGetPostProcess script from mp4_automator
[[ ! -d /config/scripts/ ]] && (mkdir /config/scripts)
[[ ! -f /config/scripts/NZBGetPostProcess.py ]] && (cp /mp4automator/NZBGetPostProcess.py /config/scripts/)

exec \
	s6-setuidgid abc /app/nzbget/nzbget -s -c /config/nzbget.conf \
	-o OutputMode=log
